version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: jobapp-postgres
    environment:
      POSTGRES_DB: employee_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5476:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - jobapp-net

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: jobapp-backend
    ports:
      - "3046:3046"
    depends_on:
      - postgres
    networks:
      - jobapp-net

  employee-ui:
    build:
      context: ./Employee-side
      dockerfile: Dockerfile
    container_name: jobapp-employee-ui
    ports:
      - "8202:80"
    networks:
      - jobapp-net

  hr-ui:
    build:
      context: ./HR-view
      dockerfile: Dockerfile
    container_name: jobapp-hr-ui
    ports:
      - "8203:80"
    networks:
      - jobapp-net

volumes:
  postgres-data:

networks:
  jobapp-net:
    driver: bridge

